config/routes.rb
DeviseApp::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :posts
  get '/users' => "posts#fetch_users", as: :fetch_users

  root :to => 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    user ||= User.new
    can :manage, Post if user.role_id == 2
    can :fetch_users, User if user.role_id == 1 # custom non-RESTful actions
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author, :description, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
    :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :role_id
  # attr_accessible :title, :body
  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.password = "dipu220191"
        user.email = auth.info.email
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #before_filter :authenticate_user!#:is_signed_in?
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  
  def github
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in Through Github!!"
      sign_in_and_redirect(:user, user)
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "You are almost Done! Please provide a password to finish setting up your account"
      redirect_to new_user_registration_url
    end
  end
  
  def google_oauth2
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in Through Github!!"
      sign_in_and_redirect(:user, user)
      #redirect_to root_url
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "You are almost Done! Please provide a password to finish setting up your account"
      redirect_to new_user_registration_url
    end
  end
  
  def facebook
    user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect(:user, user)
  end
  
#  def twitter
#    debugger
#    user = User.from_omniauth(request.env["omniauth.auth"])
#    sign_in_and_redirect(:user, user)
#  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #load_and_authorize_resource
  before_filter :authenticate_user!#:is_signed_in?
  load_and_authorize_resource :except => [:index, :fetch_users]
#  def is_signed_in?
#    redirect_to new_user_session_path unless user_signed_in?
#  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

   # authorize! :read, @post
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  def fetch_users
    @users = User.all
    authorize! :fetch_users, User
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
    <%#= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %>
    <%#= link_to "Sign in with Gogle", user_omniauth_authorize_path(:google_oauth2) %>
</div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post,  html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
    <%= f.text_field :title %>
    </div>  
  </div>
  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :author %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :description,class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
    <%= f.text_field :description %>
      </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/fetch_users.html.erb
<table style="width:300px" border ="1" class="table table-striped">
  <thead>
    <td>Email</td>
    <td>Provider</td>
    <td>Role</td>
  </thead>
  <tbody>
    <% @users.each do |user|%>
    <tr>
      <td><%= user.email%></td>
      <td><%= user.provider%></td>
      <td><%= user.role_id%></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Posts', posts_path%>

app/views/posts/index.html.erb
<%= flash[:alert] if flash[:alert]%>
<h1>Listing posts</h1>

<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.author %></td>
    <td><%= post.description %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Test Dialog', '#', {id: "show"}%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>
<% if can? :fetch_users, User %>
  <%= link_to 'All Users', fetch_users_path %>
<% end %>
<script type="text/javascript">

  
</script>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Author:</b>
  <%= @post.author %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>